#!/bin/bash

echo "WOOF: INIT"

# echo "Setting up ulimits"
# ulimit -n 40960
# ulimit -c unlimited
# ulimit -l unlimited
#

mkdir -p {{ pkg.svc_path }}/{{ cfg.path.etc }}
pushd {{ pkg.svc_path }}/{{ cfg.path.etc }} > /dev/null
ln -s {{ pkg.svc_config_path }}/config config
ln -s {{ pkg.svc_config_path }}/static_config static_config
ln -s {{ pkg.svc_config_path }}/pluggable-ui-fts.json pluggable-ui-fts.json
ln -s {{ pkg.svc_config_path }}/pluggable-ui-query.json pluggable-ui-query.json
popd > /dev/null

mkdir -p {{ pkg.svc_path }}/{{ cfg.path.default_config }}/default.d
pushd {{ pkg.svc_path }}/{{ cfg.path.default_config }} > /dev/null
ln -s {{ pkg.svc_config_path }}/default.ini default.ini

pushd default.d > /dev/null
ln -s {{ pkg.svc_config_path}}/default.d-capi.ini capi.ini
ln -s {{ pkg.svc_config_path}}/default.d-geocouch.ini geocouch.ini
popd > /dev/null

popd > /dev/null

mkdir -p {{ pkg.svc_path }}/{{ cfg.path.local_config }}
pushd {{ pkg.svc_path }}/{{ cfg.path.local_config }} > /dev/null
ln -s {{ pkg.svc_config_path }}/local.ini local.ini
popd > /dev/null
