[path]
data = "var/lib/couchbase"
logs = "var/lib/couchbase/logs"
tmp  = "var/lib/couchbase/tmp"
etc  = "var/etc/couchbase"
nodefile  = "var/lib/couchbase/couchbase-server.node"
cookiefile = "var/lib/couchbase/couchbase-server.cookie"
pidfile = "var/lib/couchbase/couchbase-server.pid"
default_config = "var/etc/couchdb"
local_config = "var/etc/couchdb"

[path.couchdb]
database_dir = "var/lib/couchdb"
view_index_dir = "var/lib/couchdb"
uri_file = "var/run/couchdb/couch.uri"
log_file = "var/log/couchdb/couch.log"

[couchdb]
log_level = "info"
